

resource_pack:
  load: .

require:
  - model_resolver.require

pipeline:
  - model_resolver.pipeline


meta:
  model_resolver:
    # load vanilla item models
    load_vanilla: false
    minecraft_version: "1.21"