

pipeline:
  - model_resolver.plugins.render_all_vanilla_gif
  - model_resolver.plugins.render_all_items_gif

output: ../../dist

meta:
  model_resolver:
    # load vanilla item models
    minecraft_version: "1.21.4"
    special_rendering: true