

minecraft: "26.1"

resource_pack:
  load: .

pipeline:
  - my_pipeline

output: ../../dist


meta:
  model_resolver:
    # load vanilla item models
    load_vanilla: false
    use_cache: true
    special_rendering: true
    preferred_minecraft_generated: "java"