name: Artifacts at every commit
on:
  workflow_dispatch:
  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Apt update
        run: | 
          sudo apt-get update -qq -y
          export DEBIAN_FRONTEND=noninteractive
      - name: Setup OpenGl
        run: | 
          sudo apt-get -y install \
            freeglut3-dev \
            libgl1-mesa-dev \
            libxcursor-dev \
            libpulse-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxv-dev \
            mesa-utils \
            libgl1-mesa-glx \
            mesa-common-dev \
            libglapi-mesa \
            libgbm1 \
            libgl1-mesa-dri \
            libsdl1.2-dev \
            libfreetype6-dev \
            xvfb \
            x11-utils

      - name: Setup cache for dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{  runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_HASH: ${{ github.sha }}
        run: |

          COMMAND="poetry run beet -l INFO -s data_pack.name=datapack -s resource_pack.name=resourcepack build"
          /usr/bin/xvfb-run -s "-screen 0 1920x1080x24 +extension GLX +extension RENDER" $COMMAND
          
      - uses: actions/upload-artifact@v3
        with:
          name: datapack
          path: build/datapack/

      - uses: actions/upload-artifact@v3
        with:
          name: resourcepack
          path: build/resourcepack/